### ISSUE TITLE
Incompatibility with Java 9 - JRE Path changed

### ISSUE THREAD

**Issue by cthoyt** [kivy/pyjnius#304] opened 2017-10-19 08:16 UTC
PyJnius looks for the path 

`/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/jre/lib/server/libjvm.dylib`

but the `jre` folder doesn't exist in this hierarchy anymore and it should look for

`/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/libjvm.dylib`

**Comment by inclement** [comment] 2017-10-19 18:09
Looks like this just needs a small change at https://github.com/kivy/pyjnius/blob/master/setup.py#L82 , but I'm not sure exactly what should be different (e.g. is this a new condition if `framework` has a certain value?). Would you be able to post the output of `/usr/libexec/java_home`?

**Comment by cthoyt** [comment] 2017-10-20 07:19
```sh
$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
```

As a fun note, in the past you had to do `/usr/libexec/java_home -v 1.8` but now you have to do `/usr/libexec/java_home -v 9`. Looks like they've committed to a new versioning scheme.

**Comment by cthoyt** [comment] 2018-02-05 15:38
Hi @inclement, I'm just coming back to this now. Was this feedback enough to make an update?

**Comment by akshaysharma096** [comment] 2018-04-13 22:12
Guys, any update ?

**Comment by KeyWeeUsr** [comment] 2018-11-17 00:00
Just `Ctrl`+`F` for `libjvm.so`, but yeah, it's since 9:
https://packages.ubuntu.com/bionic/amd64/openjdk-8-jre-headless/filelist
https://packages.ubuntu.com/cosmic/amd64/openjdk-11-jre-headless/filelist

**Comment by hadim** [comment] 2018-11-21 16:14
That bug will also affect the usage of Java >= 9 using the soon-to-be-released conda-forge builds: https://github.com/conda-forge/openjdk-feedstock/pull/34, https://github.com/conda-forge/openjdk-feedstock/pull/35, https://github.com/conda-forge/openjdk-feedstock/pull/36

**Comment by hadim** [comment] 2018-11-22 17:35
Fixed in https://github.com/kivy/pyjnius/pull/363

**Closed** 2018-11-24 09:57 UTC
Labels: bug

**Comment by KeyWeeUsr** [comment] 2018-12-28 09:15
@rhoerbe Could you please link some official documentation/changelog why this change happened. I'm curious if it has other implications for the whole system and not Java only.

**Comment by rhoerbe** [comment] 2018-12-28 10:45
The issue occurred within the Pycharm IDE in a rather bulky project that is not suitable to isolate the issue. When creating a separate demo-repo I was unable to reproduce it. 

Now I am a few commits ahead, and changed the Django-settings, and cannot reproduce the issue in my main project any more. There are a couple of combinations to test to reproduce - I gave up. 

What I can describe is that downgrading pyjnius from 1.1.4 to 1.1.3 fixed the issue. However, to reproduce it there seem be other factors than JRE 1.8 and DYLD_LIBRARY_PATH.
