### ISSUE TITLE
Tests fail with Java 8 and Python 3.6

### ISSUE THREAD

**Issue by rapgro** [kivy/pyjnius#305] opened 2017-10-24 09:44 UTC
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

python3-3.6.3-2.fc27.x86_64
python3-nose-1.3.7-15.fc27.noarch

```
ERROR: test_multiple_methods (test_method_multiple_signatures.MultipleSignature)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/builder/rpmbuild/BUILD/python-jnius-1.1.1/python3/tests/test_method_multiple_signatures.py", line 19, in test_multiple_methods
    self.assertEquals(s.getBytes('utf8'), [104, 101, 108, 108, 111])
  File "jnius/jnius_export_class.pxi", line 906, in jnius.JavaMultipleMethod.__call__
  File "jnius/jnius_export_class.pxi", line 638, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 725, in jnius.JavaMethod.call_method
  File "jnius/jnius_utils.pxi", line 93, in jnius.check_exception
jnius.JavaException: JVM exception occurred: å

======================================================================
FAIL: test_instances_methods_params (test_basics.BasicsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/builder/rpmbuild/BUILD/python-jnius-1.1.1/python3/tests/test_basics.py", line 104, in test_instances_methods_params
    self.assertEquals(test.methodParamsString('helloworld'), True)
AssertionError: False != True

======================================================================
FAIL: test_create_bytearray (test_bytearray.StringArgumentForByteArrayTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/builder/rpmbuild/BUILD/python-jnius-1.1.1/python3/tests/test_bytearray.py", line 31, in test_create_bytearray
    self.assertEquals(nis.read(barr, 0, 5), 5)
AssertionError: 3 != 5

======================================================================
FAIL: test_stack (test_reflect.ReflectTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/builder/rpmbuild/BUILD/python-jnius-1.1.1/python3/tests/test_reflect.py", line 15, in test_stack
    self.assertEqual(stack.pop(), 'world')
AssertionError: 'å\x1c\x1a±' != 'world'
+ world- å- ▒±
```

**Comment by Arnie97** [comment] 2018-04-30 09:52
Seems to be a duplicate of #300.

**Comment by KeyWeeUsr** [comment] 2018-11-29 20:44
Yup, duplicate.

**Closed by KeyWeeUsr** 2018-11-29 20:44 UTC
