### ISSUE TITLE
Quick Start Example - python 3.6

### ISSUE THREAD

**Issue by DaveO-Home** [kivy/pyjnius#339] opened 2018-05-09 17:29 UTC
Your quick start works better with;
String = autoclass('java.lang.String')
stack.push(String("hello"))

Spent some time trying to decode() this.

**Comment by Arnie97** [comment] 2018-05-26 20:32
Duplicate of #334.

@tito Is there any release schedule for the next version please? We have received dozens of complaints about #300.

**Closed** 2018-11-29 20:54 UTC
Labels: bug, duplicate, examples
