### ISSUE TITLE
Get exception message of python in java

### ISSUE THREAD

**Issue by OptimusV5** [kivy/pyjnius#407] opened 2019-02-15 10:41 UTC
I have an java interface which is implemented in python, and I call the python function in a java program. I am trying to catch the exceptions that python code throw in my java program. I've tried the `JavaException` class, but makes no sense.
So, how can i get the python exception info in java?

**Comment by Julian-O** [comment] 2023-10-28 02:08
Duplicate of #623 which is to document how to do this.

**Closed by Julian-O** 2023-10-28 02:08 UTC
Labels: duplicate, enhancement
