### ISSUE TITLE
Inspect Java method arguments and return type

### ISSUE THREAD

**Issue by JPDSousa** [kivy/pyjnius#419] opened 2019-05-09 13:07 UTC
I'm working on a python tool on top of pyjnius. One of my technical requirements is to preprocess python objects based on the meta-information of a given java method.

For this I tried to access this data through `JavaMethod` (e.g. `object.hashCode` will return a JavaMethod). The thing is that I can't seem to access any information of the java method through `JavaMethod`. By doing `dir(object.hashCode)` I only get python related stuff.

Now, by inspecting the java method class, and bear with me as I'm not a cython expert, I see that I have a field [here](https://github.com/kivy/pyjnius/blob/master/jnius/jnius_export_class.pxi#L678) which points me to the fact that if what I want is not available today, it can be achieved.

Can I get some more insights on this? I might be able to help with a merge request.

**Comment by amsukdu** [comment] 2019-05-18 04:54
Hello sir,
I think this is a great idea and want to solve this issue. 
Poked around the source code and it seems that I can add the dunders(__dir__, __repr__, __str__, etc...) to JavaMethod python object.

My opinion is that __repr__ or __str__ will be more appropriate to express signature than __dir__. 
Secondly, the signature will be more informative if it is Java type like "method(String, Integer) -> String".

What are your thoughts? Please let me know! 😄

**Comment by JPDSousa** [comment] 2019-05-18 05:56
I agree that we might want to change `str` and `repr`, but since both of those methods will return a string, iterating over the list of arguments will be a bit trickier. My idea is to have that `definition_args` field accessible from the Python instance in the form of an array of `JavaClass` instances, or something similar.

What do you think? Does this match your expectations?

**Comment by amsukdu** [comment] 2019-05-18 08:03
Yeah, you're right. One huge string would be troublesome.

```python
from jnius import autoclass
cls = autoclass('java.lang.String')
dir(cls.substring)
#['(I)Ljava/lang/String;', '(II)Ljava/lang/String;']
dir(cls.valueOf)
'''
['(C)Ljava/lang/String;',
 '(D)Ljava/lang/String;',
 '(F)Ljava/lang/String;',
 '(I)Ljava/lang/String;',
 '(J)Ljava/lang/String;',
 '(Ljava/lang/Object;)Ljava/lang/String;',
 '(Z)Ljava/lang/String;',
 '([C)Ljava/lang/String;',
 '([CII)Ljava/lang/String;']
'''
```

The expression is from JNI(I think...).

**Comment by JPDSousa** [comment] 2019-05-18 12:14
I don't know if by intention, but you actually touched a very important point: method overloads. So maybe my initial idea wouldn't be that useable. Maybe instead of having an array of arguments, we should have a matrix (or array of arrays) where each array represents the param list for one overload. Does that make sense?

**Comment by amsukdu** [comment] 2019-05-18 13:41
Yes, NOW I fully understand what you need.
I assume you originally wanted to get an argument list with types from `__dir__` and do some useful stuff by iterate over this list. But considering the overloads, you think you have to make another dimension to get this, right? I thought this suggestion was for obtaining function signature, to simply become free from Java API doc 🤷‍♂ 

How about this?
```python
[(args=['int[]', 'float'], rtn=None), (args=[], rtn='Int')]
```
`collections.namedtuple` could be great in this situation. `dict` would be fine also.

However, there is another problem, VarArgs. 

```python
dir(cls.out.printf)
'''
['(Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintStream;',
 '(Ljava/util/Locale;Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintStream;']
'''
```
[JNI Type Signature](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/types.html)
![image](https://user-images.githubusercontent.com/6724600/57970413-02d77d00-79bc-11e9-9d5e-8e351cf0635f.png)

Luckily, there is a flag for VarArgs but as you can see,  the expression is same as an array...
How about this if it is a VarArgs?
```python
[(args=['java.lang.String', 'java.lang.Object*'], rtn=None)]
```

If you think this expression couldn't be that useful for your needs, I just want to do like this
```python
['(int, int[]) -> None', '(int, int:VarArgs) -> java.lang.String']
```

**Comment by JPDSousa** [comment] 2019-05-21 09:22
> [(args=['int[]', 'float'], rtn=None), (args=[], rtn='Int')]

This sounds useful enough, indeed. I would just have to transform the JNI representations into something useful (python-speaking).

> However, there is another problem, VarArgs.

I don't know how problematic this is. What if we treat varargs as object arrays? Java doesn't let you have a given method with both varargs of type A and object array of type A:

```java
private void m(final Object... var) { }

private void m(final Object[] var) { }
```
(the compiler complains about method duplication)

> If you think this expression couldn't be that useful for your needs, I just want to do like this
> ['(int, int[]) -> None', '(int, int:VarArgs) -> java.lang.String']

This is not that useful for me because I would have to parte the content of the strings... but I  guess that we can build "my feature" and then yours can derive from it.

**Comment by amsukdu** [comment] 2019-05-21 10:24
The problem is that Varargs and array are same in JNI expression.
`['(Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintStream;',`
is the [System.out.printf](https://docs.oracle.com/javase/9/docs/api/java/io/PrintStream.html#printf-java.lang.String-java.lang.Object...-) JNI expression and it will crash if you call it with an array.

`[(args=['java.lang.String', 'java.lang.Object*'], rtn=None)]`

Seems pretty pythonic to me.

**Comment by JPDSousa** [comment] 2019-05-21 18:21
Sure, I have no objection :smile: what are the next steps then?

**Comment by amsukdu** [comment] 2019-05-21 22:39
Um... I'll make a PR shortly! Can you reach out the maintainer or reviewer for this kind of PR?

**Comment by JPDSousa** [comment] 2019-05-22 08:51
I'm not sure I understand your question. I'm not a maintainer of this project, but I can surely be a reviewer for the PR (and do some preliminary live testing)

**Comment by tshirtman** [comment] 2019-12-15 10:07
Hello, i'm now looking at this, and while i like the feature, i'm uncomfortable with overriding the behavior of `__dir__` especially as these signatures are not really members of the method you can access, they are different ways to call it, so it does seem too much of a twist to me, any objection to instead exposing that as a `signatures` method on both classes? https://github.com/kivy/pyjnius/pull/467

**Comment by JPDSousa** [comment] 2019-12-16 09:23
Hey Gabriel! Sorry for the late response and overall silence in regards to this thread. My intention with this feature was to simply inspect the arguments of a given JavaMethod. I understand your argument, and I also agree that it makes more sense to have a dedicated endpoint to access the signature of a given method.

Thanks for the final push on this issue! When can we see this in a new pyjnius release? ;)

**Comment by tshirtman** [comment] 2019-12-16 23:10
No worries, sorry for being slow to answer in the first place! I think i'll try to fix at least a bug i added in current version before doing the release, but hopefully that won't be too long :).

**Comment by tshirtman** [comment] 2019-12-16 23:11
closing this since it's been fixed.

**Closed by tshirtman** 2019-12-16 23:11 UTC
