### ISSUE TITLE
[BUG] System.gc() makes Pyjnius stuck

### ISSUE THREAD

**Issue by EKami** [kivy/pyjnius#350] opened 2018-08-06 16:53 UTC
Hello,
I just noticed that each time I add `System.gc()` in my java code Pyjnius gets stuck. There is no error, nothing on the output, only a stuck program waiting indefinitely.

**Comment by KeyWeeUsr** [comment] 2019-01-31 00:01
Without an example it's quite hard to reproduce. I tried to put `System.gc()` to lot of places, but nothing really happened. I think it might be due to #371 merged, which might have collected the references from the Java side, but left some trash in Python or just caused JNI to crash pyjnius. Try to install the latest version, try again to reproduce and please post a reproducible example.

**Closed by KeyWeeUsr** 2019-01-31 00:01 UTC
Labels: documentation, question, support
